-- Enhance Polls Migration: add poll types, blind polls, and option metadata
-- Note: golang-migrate wraps each migration in a transaction automatically.
-- Do NOT add BEGIN/COMMIT here.

-- Add poll_type column with CHECK constraint
ALTER TABLE polls ADD COLUMN poll_type VARCHAR(20) NOT NULL DEFAULT 'standard';
ALTER TABLE polls ADD CONSTRAINT chk_poll_type
    CHECK (poll_type IN ('standard', 'binary', 'emoji', 'schedule', 'vibe_check'));

-- Add is_blind column
ALTER TABLE polls ADD COLUMN is_blind BOOLEAN NOT NULL DEFAULT FALSE;

-- Add option_metadata JSONB to poll_options (nullable, for image URLs, coordinates, etc.)
ALTER TABLE poll_options ADD COLUMN option_metadata JSONB;

-- Drop the UNIQUE(poll_id, text) constraint on poll_options.
-- This blocks duplicate emoji options (e.g. two options with the same emoji text).
-- The constraint name was auto-generated by CREATE TABLE in 000007.
ALTER TABLE poll_options DROP CONSTRAINT IF EXISTS poll_options_poll_id_text_key;

-- Index for filtering by poll_type
CREATE INDEX IF NOT EXISTS idx_polls_poll_type ON polls(poll_type) WHERE deleted_at IS NULL;
