server:
  environment: development
  port: '8080'
  allowed_origins: ["*"]
  jwt_secret_key: "dev-secret-key"
  frontend_url: "https://nomadcrew.uk"
  log_level: "debug"

database:
  host: postgres
  port: '5432'
  user: postgres
  password: admin123
  name: nomadcrew
  max_connections: 20
  ssl_mode: disable

redis:
  address: "redis:6379"
  password: "redispass"
  db: 0

email:
  from_address: "welcome@nomadcrew.uk"
  from_name: "NomadCrew"
  resend_api_key: "re_gSHe3f7K_DtdwPAc7u5PsCDLFCvJAMmLR"

external_services:
  geoapify_key: "3caea35bf49648c99db5d26cdcdd914a"
  pexels_api_key: "imG6TzlCZqyPEF7Tjp41RGJsqPqZFyuALhrtqI5qr04xyhCYwjXDnImo"
  supabase_anon_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmbXFpbHRkYWp2cWVubmRteWx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyMzYxMTQsImV4cCI6MjA1MDgxMjExNH0.f2EbHa9Lwv-euLbj5bFiFixCHhnUREARg51qa469T_o"
  supabase_url: "https://efmqiltdajvqenndmylz.supabase.co"
  supabase_jwt_secret: "KwiMJ4NKJW/FFE41DNj5C6fj19mww+ydxyesjZUG+UZ2rHKnTTTf2NkDxv1QTgpM06JDcwdEJJioAIeP5AMO/w=="
  jwt_secret_key: "d984YOT9SPEilfksihdOmKgNzXJzo5AiJXquE2yEvMG3jd1urk6HByIWkU4B6l5"
