server:
  environment: production
  port: 8080
  allowed_origins: # Set through env vars
  jwt_secret_key: # Set through env vars

database:
  host: # Set through env vars
  port: # Set through env vars
  user: # Set through env vars
  password: # Set through env vars
  name: # Set through env vars
  max_connections: 50
  ssl_mode: require

redis:
  address: # Set through env vars
  password: # Set through env vars
  db: 0