// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChatGroupMember = `-- name: AddChatGroupMember :exec
INSERT INTO chat_group_members (group_id, user_id)
VALUES ($1, $2)
ON CONFLICT (group_id, user_id) DO NOTHING
`

type AddChatGroupMemberParams struct {
	GroupID string `db:"group_id" json:"group_id"`
	UserID  string `db:"user_id" json:"user_id"`
}

func (q *Queries) AddChatGroupMember(ctx context.Context, arg AddChatGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addChatGroupMember, arg.GroupID, arg.UserID)
	return err
}

const addMessageReaction = `-- name: AddMessageReaction :exec
INSERT INTO chat_message_reactions (message_id, user_id, reaction)
VALUES ($1, $2, $3)
ON CONFLICT (message_id, user_id, reaction) DO NOTHING
`

type AddMessageReactionParams struct {
	MessageID string `db:"message_id" json:"message_id"`
	UserID    string `db:"user_id" json:"user_id"`
	Reaction  string `db:"reaction" json:"reaction"`
}

func (q *Queries) AddMessageReaction(ctx context.Context, arg AddMessageReactionParams) error {
	_, err := q.db.Exec(ctx, addMessageReaction, arg.MessageID, arg.UserID, arg.Reaction)
	return err
}

const countUnreadMessages = `-- name: CountUnreadMessages :one
SELECT COUNT(*) as count
FROM chat_messages cm
INNER JOIN chat_group_members cgm ON cm.group_id = cgm.group_id
WHERE cgm.group_id = $1
    AND cgm.user_id = $2
    AND cm.deleted_at IS NULL
    AND (cgm.last_read_message_id IS NULL OR cm.id > cgm.last_read_message_id)
`

type CountUnreadMessagesParams struct {
	GroupID string `db:"group_id" json:"group_id"`
	UserID  string `db:"user_id" json:"user_id"`
}

func (q *Queries) CountUnreadMessages(ctx context.Context, arg CountUnreadMessagesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadMessages, arg.GroupID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChatGroup = `-- name: CreateChatGroup :one

INSERT INTO chat_groups (trip_id, name, description, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateChatGroupParams struct {
	TripID      string  `db:"trip_id" json:"trip_id"`
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
	CreatedBy   *string `db:"created_by" json:"created_by"`
}

// Chat Operations
func (q *Queries) CreateChatGroup(ctx context.Context, arg CreateChatGroupParams) (string, error) {
	row := q.db.QueryRow(ctx, createChatGroup,
		arg.TripID,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (group_id, user_id, content, content_type)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateChatMessageParams struct {
	GroupID     string  `db:"group_id" json:"group_id"`
	UserID      *string `db:"user_id" json:"user_id"`
	Content     string  `db:"content" json:"content"`
	ContentType string  `db:"content_type" json:"content_type"`
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (string, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.GroupID,
		arg.UserID,
		arg.Content,
		arg.ContentType,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getChatGroup = `-- name: GetChatGroup :one
SELECT
    id, trip_id, name,
    COALESCE(description, '') as description,
    created_by, created_at, updated_at
FROM chat_groups
WHERE id = $1 AND deleted_at IS NULL
`

type GetChatGroupRow struct {
	ID          string             `db:"id" json:"id"`
	TripID      string             `db:"trip_id" json:"trip_id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	CreatedBy   *string            `db:"created_by" json:"created_by"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetChatGroup(ctx context.Context, id string) (*GetChatGroupRow, error) {
	row := q.db.QueryRow(ctx, getChatGroup, id)
	var i GetChatGroupRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getChatGroupByTrip = `-- name: GetChatGroupByTrip :one
SELECT
    id, trip_id, name,
    COALESCE(description, '') as description,
    created_by, created_at, updated_at
FROM chat_groups
WHERE trip_id = $1 AND deleted_at IS NULL
LIMIT 1
`

type GetChatGroupByTripRow struct {
	ID          string             `db:"id" json:"id"`
	TripID      string             `db:"trip_id" json:"trip_id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	CreatedBy   *string            `db:"created_by" json:"created_by"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetChatGroupByTrip(ctx context.Context, tripID string) (*GetChatGroupByTripRow, error) {
	row := q.db.QueryRow(ctx, getChatGroupByTrip, tripID)
	var i GetChatGroupByTripRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getChatGroupMembers = `-- name: GetChatGroupMembers :many
SELECT
    cgm.group_id, cgm.user_id, cgm.joined_at, cgm.last_read_message_id
FROM chat_group_members cgm
WHERE cgm.group_id = $1
`

func (q *Queries) GetChatGroupMembers(ctx context.Context, groupID string) ([]*ChatGroupMember, error) {
	rows, err := q.db.Query(ctx, getChatGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ChatGroupMember{}
	for rows.Next() {
		var i ChatGroupMember
		if err := rows.Scan(
			&i.GroupID,
			&i.UserID,
			&i.JoinedAt,
			&i.LastReadMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMessage = `-- name: GetChatMessage :one
SELECT
    id, group_id, user_id, content, content_type, created_at, updated_at
FROM chat_messages
WHERE id = $1 AND deleted_at IS NULL
`

type GetChatMessageRow struct {
	ID          string             `db:"id" json:"id"`
	GroupID     string             `db:"group_id" json:"group_id"`
	UserID      *string            `db:"user_id" json:"user_id"`
	Content     string             `db:"content" json:"content"`
	ContentType string             `db:"content_type" json:"content_type"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetChatMessage(ctx context.Context, id string) (*GetChatMessageRow, error) {
	row := q.db.QueryRow(ctx, getChatMessage, id)
	var i GetChatMessageRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Content,
		&i.ContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getChatMessages = `-- name: GetChatMessages :many
SELECT
    id, group_id, user_id, content, content_type, created_at, updated_at
FROM chat_messages
WHERE group_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetChatMessagesParams struct {
	GroupID string `db:"group_id" json:"group_id"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

type GetChatMessagesRow struct {
	ID          string             `db:"id" json:"id"`
	GroupID     string             `db:"group_id" json:"group_id"`
	UserID      *string            `db:"user_id" json:"user_id"`
	Content     string             `db:"content" json:"content"`
	ContentType string             `db:"content_type" json:"content_type"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]*GetChatMessagesRow, error) {
	rows, err := q.db.Query(ctx, getChatMessages, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetChatMessagesRow{}
	for rows.Next() {
		var i GetChatMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Content,
			&i.ContentType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatMessagesAfter = `-- name: GetChatMessagesAfter :many
SELECT
    id, group_id, user_id, content, content_type, created_at, updated_at
FROM chat_messages
WHERE group_id = $1 AND created_at > $2 AND deleted_at IS NULL
ORDER BY created_at ASC
`

type GetChatMessagesAfterParams struct {
	GroupID   string             `db:"group_id" json:"group_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type GetChatMessagesAfterRow struct {
	ID          string             `db:"id" json:"id"`
	GroupID     string             `db:"group_id" json:"group_id"`
	UserID      *string            `db:"user_id" json:"user_id"`
	Content     string             `db:"content" json:"content"`
	ContentType string             `db:"content_type" json:"content_type"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Get messages after a specific timestamp (for real-time updates)
func (q *Queries) GetChatMessagesAfter(ctx context.Context, arg GetChatMessagesAfterParams) ([]*GetChatMessagesAfterRow, error) {
	rows, err := q.db.Query(ctx, getChatMessagesAfter, arg.GroupID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetChatMessagesAfterRow{}
	for rows.Next() {
		var i GetChatMessagesAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Content,
			&i.ContentType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastReadMessageID = `-- name: GetLastReadMessageID :one
SELECT last_read_message_id
FROM chat_group_members
WHERE group_id = $1 AND user_id = $2
`

type GetLastReadMessageIDParams struct {
	GroupID string `db:"group_id" json:"group_id"`
	UserID  string `db:"user_id" json:"user_id"`
}

func (q *Queries) GetLastReadMessageID(ctx context.Context, arg GetLastReadMessageIDParams) (*string, error) {
	row := q.db.QueryRow(ctx, getLastReadMessageID, arg.GroupID, arg.UserID)
	var last_read_message_id *string
	err := row.Scan(&last_read_message_id)
	return last_read_message_id, err
}

const getMessageReactions = `-- name: GetMessageReactions :many
SELECT message_id, user_id, reaction, created_at
FROM chat_message_reactions
WHERE message_id = $1
`

func (q *Queries) GetMessageReactions(ctx context.Context, messageID string) ([]*ChatMessageReaction, error) {
	rows, err := q.db.Query(ctx, getMessageReactions, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ChatMessageReaction{}
	for rows.Next() {
		var i ChatMessageReaction
		if err := rows.Scan(
			&i.MessageID,
			&i.UserID,
			&i.Reaction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeChatGroupMember = `-- name: RemoveChatGroupMember :exec
DELETE FROM chat_group_members
WHERE group_id = $1 AND user_id = $2
`

type RemoveChatGroupMemberParams struct {
	GroupID string `db:"group_id" json:"group_id"`
	UserID  string `db:"user_id" json:"user_id"`
}

func (q *Queries) RemoveChatGroupMember(ctx context.Context, arg RemoveChatGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeChatGroupMember, arg.GroupID, arg.UserID)
	return err
}

const removeMessageReaction = `-- name: RemoveMessageReaction :exec
DELETE FROM chat_message_reactions
WHERE message_id = $1 AND user_id = $2 AND reaction = $3
`

type RemoveMessageReactionParams struct {
	MessageID string `db:"message_id" json:"message_id"`
	UserID    string `db:"user_id" json:"user_id"`
	Reaction  string `db:"reaction" json:"reaction"`
}

func (q *Queries) RemoveMessageReaction(ctx context.Context, arg RemoveMessageReactionParams) error {
	_, err := q.db.Exec(ctx, removeMessageReaction, arg.MessageID, arg.UserID, arg.Reaction)
	return err
}

const softDeleteChatMessage = `-- name: SoftDeleteChatMessage :exec
UPDATE chat_messages
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteChatMessageParams struct {
	ID     string  `db:"id" json:"id"`
	UserID *string `db:"user_id" json:"user_id"`
}

func (q *Queries) SoftDeleteChatMessage(ctx context.Context, arg SoftDeleteChatMessageParams) error {
	_, err := q.db.Exec(ctx, softDeleteChatMessage, arg.ID, arg.UserID)
	return err
}

const updateLastReadMessage = `-- name: UpdateLastReadMessage :exec
UPDATE chat_group_members
SET last_read_message_id = $3
WHERE group_id = $1 AND user_id = $2
`

type UpdateLastReadMessageParams struct {
	GroupID           string  `db:"group_id" json:"group_id"`
	UserID            string  `db:"user_id" json:"user_id"`
	LastReadMessageID *string `db:"last_read_message_id" json:"last_read_message_id"`
}

func (q *Queries) UpdateLastReadMessage(ctx context.Context, arg UpdateLastReadMessageParams) error {
	_, err := q.db.Exec(ctx, updateLastReadMessage, arg.GroupID, arg.UserID, arg.LastReadMessageID)
	return err
}
