// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingInvitationsForTrip = `-- name: CountPendingInvitationsForTrip :one
SELECT COUNT(*) as count
FROM trip_invitations
WHERE trip_id = $1 AND status = 'PENDING'
`

func (q *Queries) CountPendingInvitationsForTrip(ctx context.Context, tripID string) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingInvitationsForTrip, tripID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvitation = `-- name: CreateInvitation :one

INSERT INTO trip_invitations
    (id, trip_id, inviter_id, invitee_email, role, token, status, expires_at)
VALUES
    ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateInvitationParams struct {
	ID           string             `db:"id" json:"id"`
	TripID       string             `db:"trip_id" json:"trip_id"`
	InviterID    *string            `db:"inviter_id" json:"inviter_id"`
	InviteeEmail string             `db:"invitee_email" json:"invitee_email"`
	Role         MembershipRole     `db:"role" json:"role"`
	Token        *string            `db:"token" json:"token"`
	Status       InvitationStatus   `db:"status" json:"status"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

// Trip Invitations Operations
func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (string, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.TripID,
		arg.InviterID,
		arg.InviteeEmail,
		arg.Role,
		arg.Token,
		arg.Status,
		arg.ExpiresAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredInvitations = `-- name: DeleteExpiredInvitations :exec
UPDATE trip_invitations
SET status = 'DECLINED', updated_at = CURRENT_TIMESTAMP
WHERE status = 'PENDING' AND expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredInvitations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredInvitations)
	return err
}

const getInvitation = `-- name: GetInvitation :one
SELECT
    id, trip_id, inviter_id, invitee_email, role, token, status,
    expires_at, created_at, updated_at
FROM trip_invitations
WHERE id = $1
`

type GetInvitationRow struct {
	ID           string             `db:"id" json:"id"`
	TripID       string             `db:"trip_id" json:"trip_id"`
	InviterID    *string            `db:"inviter_id" json:"inviter_id"`
	InviteeEmail string             `db:"invitee_email" json:"invitee_email"`
	Role         MembershipRole     `db:"role" json:"role"`
	Token        *string            `db:"token" json:"token"`
	Status       InvitationStatus   `db:"status" json:"status"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetInvitation(ctx context.Context, id string) (*GetInvitationRow, error) {
	row := q.db.QueryRow(ctx, getInvitation, id)
	var i GetInvitationRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.InviterID,
		&i.InviteeEmail,
		&i.Role,
		&i.Token,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT
    id, trip_id, inviter_id, invitee_email, role, token, status,
    expires_at, created_at, updated_at
FROM trip_invitations
WHERE token = $1
`

type GetInvitationByTokenRow struct {
	ID           string             `db:"id" json:"id"`
	TripID       string             `db:"trip_id" json:"trip_id"`
	InviterID    *string            `db:"inviter_id" json:"inviter_id"`
	InviteeEmail string             `db:"invitee_email" json:"invitee_email"`
	Role         MembershipRole     `db:"role" json:"role"`
	Token        *string            `db:"token" json:"token"`
	Status       InvitationStatus   `db:"status" json:"status"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetInvitationByToken(ctx context.Context, token *string) (*GetInvitationByTokenRow, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i GetInvitationByTokenRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.InviterID,
		&i.InviteeEmail,
		&i.Role,
		&i.Token,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getInvitationsByTripID = `-- name: GetInvitationsByTripID :many
SELECT
    id, trip_id, inviter_id, invitee_email, role, token, status,
    expires_at, created_at, updated_at
FROM trip_invitations
WHERE trip_id = $1
ORDER BY created_at DESC
`

type GetInvitationsByTripIDRow struct {
	ID           string             `db:"id" json:"id"`
	TripID       string             `db:"trip_id" json:"trip_id"`
	InviterID    *string            `db:"inviter_id" json:"inviter_id"`
	InviteeEmail string             `db:"invitee_email" json:"invitee_email"`
	Role         MembershipRole     `db:"role" json:"role"`
	Token        *string            `db:"token" json:"token"`
	Status       InvitationStatus   `db:"status" json:"status"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetInvitationsByTripID(ctx context.Context, tripID string) ([]*GetInvitationsByTripIDRow, error) {
	rows, err := q.db.Query(ctx, getInvitationsByTripID, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetInvitationsByTripIDRow{}
	for rows.Next() {
		var i GetInvitationsByTripIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.InviterID,
			&i.InviteeEmail,
			&i.Role,
			&i.Token,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingInvitationsForUser = `-- name: GetPendingInvitationsForUser :many
SELECT
    id, trip_id, inviter_id, invitee_email, role, token, status,
    expires_at, created_at, updated_at
FROM trip_invitations
WHERE invitee_email = $1 AND status = 'PENDING' AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC
`

type GetPendingInvitationsForUserRow struct {
	ID           string             `db:"id" json:"id"`
	TripID       string             `db:"trip_id" json:"trip_id"`
	InviterID    *string            `db:"inviter_id" json:"inviter_id"`
	InviteeEmail string             `db:"invitee_email" json:"invitee_email"`
	Role         MembershipRole     `db:"role" json:"role"`
	Token        *string            `db:"token" json:"token"`
	Status       InvitationStatus   `db:"status" json:"status"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetPendingInvitationsForUser(ctx context.Context, inviteeEmail string) ([]*GetPendingInvitationsForUserRow, error) {
	rows, err := q.db.Query(ctx, getPendingInvitationsForUser, inviteeEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetPendingInvitationsForUserRow{}
	for rows.Next() {
		var i GetPendingInvitationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.InviterID,
			&i.InviteeEmail,
			&i.Role,
			&i.Token,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvitationStatus = `-- name: UpdateInvitationStatus :exec
UPDATE trip_invitations
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateInvitationStatusParams struct {
	ID     string           `db:"id" json:"id"`
	Status InvitationStatus `db:"status" json:"status"`
}

func (q *Queries) UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) error {
	_, err := q.db.Exec(ctx, updateInvitationStatus, arg.ID, arg.Status)
	return err
}
