// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTripMembers = `-- name: CountTripMembers :one
SELECT COUNT(*) as count
FROM trip_memberships
WHERE trip_id = $1 AND status = 'ACTIVE'
`

func (q *Queries) CountTripMembers(ctx context.Context, tripID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTripMembers, tripID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :exec

INSERT INTO trip_memberships (trip_id, user_id, role, status)
VALUES ($1, $2, $3, $4)
`

type CreateMembershipParams struct {
	TripID string           `db:"trip_id" json:"trip_id"`
	UserID string           `db:"user_id" json:"user_id"`
	Role   MembershipRole   `db:"role" json:"role"`
	Status MembershipStatus `db:"status" json:"status"`
}

// Trip Memberships Operations
func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership,
		arg.TripID,
		arg.UserID,
		arg.Role,
		arg.Status,
	)
	return err
}

const deactivateMembership = `-- name: DeactivateMembership :exec
UPDATE trip_memberships
SET status = 'INACTIVE', updated_at = CURRENT_TIMESTAMP
WHERE trip_id = $1 AND user_id = $2 AND status = 'ACTIVE'
`

type DeactivateMembershipParams struct {
	TripID string `db:"trip_id" json:"trip_id"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) DeactivateMembership(ctx context.Context, arg DeactivateMembershipParams) error {
	_, err := q.db.Exec(ctx, deactivateMembership, arg.TripID, arg.UserID)
	return err
}

const getActiveMembership = `-- name: GetActiveMembership :one
SELECT id, trip_id, user_id, role, status, created_at, updated_at
FROM trip_memberships
WHERE trip_id = $1 AND user_id = $2 AND status = 'ACTIVE'
`

type GetActiveMembershipParams struct {
	TripID string `db:"trip_id" json:"trip_id"`
	UserID string `db:"user_id" json:"user_id"`
}

type GetActiveMembershipRow struct {
	ID        string           `db:"id" json:"id"`
	TripID    string           `db:"trip_id" json:"trip_id"`
	UserID    string           `db:"user_id" json:"user_id"`
	Role      MembershipRole   `db:"role" json:"role"`
	Status    MembershipStatus `db:"status" json:"status"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetActiveMembership(ctx context.Context, arg GetActiveMembershipParams) (*GetActiveMembershipRow, error) {
	row := q.db.QueryRow(ctx, getActiveMembership, arg.TripID, arg.UserID)
	var i GetActiveMembershipRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMemberWithUserDetails = `-- name: GetMemberWithUserDetails :many
SELECT
    tm.id,
    tm.trip_id,
    tm.user_id,
    tm.role,
    tm.status,
    tm.created_at,
    tm.updated_at,
    up.email,
    up.username,
    COALESCE(up.first_name, '') as first_name,
    COALESCE(up.last_name, '') as last_name,
    COALESCE(up.avatar_url, '') as avatar_url
FROM trip_memberships tm
INNER JOIN user_profiles up ON tm.user_id = up.id
WHERE tm.trip_id = $1 AND tm.status = 'ACTIVE'
ORDER BY tm.created_at ASC
`

type GetMemberWithUserDetailsRow struct {
	ID        string           `db:"id" json:"id"`
	TripID    string           `db:"trip_id" json:"trip_id"`
	UserID    string           `db:"user_id" json:"user_id"`
	Role      MembershipRole   `db:"role" json:"role"`
	Status    MembershipStatus `db:"status" json:"status"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	Email     string           `db:"email" json:"email"`
	Username  string           `db:"username" json:"username"`
	FirstName string           `db:"first_name" json:"first_name"`
	LastName  string           `db:"last_name" json:"last_name"`
	AvatarUrl string           `db:"avatar_url" json:"avatar_url"`
}

// Get members with user profile information
func (q *Queries) GetMemberWithUserDetails(ctx context.Context, tripID string) ([]*GetMemberWithUserDetailsRow, error) {
	rows, err := q.db.Query(ctx, getMemberWithUserDetails, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetMemberWithUserDetailsRow{}
	for rows.Next() {
		var i GetMemberWithUserDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembership = `-- name: GetMembership :one
SELECT id, trip_id, user_id, role, status, created_at, updated_at
FROM trip_memberships
WHERE trip_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	TripID string `db:"trip_id" json:"trip_id"`
	UserID string `db:"user_id" json:"user_id"`
}

type GetMembershipRow struct {
	ID        string           `db:"id" json:"id"`
	TripID    string           `db:"trip_id" json:"trip_id"`
	UserID    string           `db:"user_id" json:"user_id"`
	Role      MembershipRole   `db:"role" json:"role"`
	Status    MembershipStatus `db:"status" json:"status"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (*GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.TripID, arg.UserID)
	var i GetMembershipRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTripMembers = `-- name: GetTripMembers :many
SELECT id, trip_id, user_id, role, status, created_at, updated_at
FROM trip_memberships
WHERE trip_id = $1 AND status = 'ACTIVE'
ORDER BY created_at ASC
`

type GetTripMembersRow struct {
	ID        string           `db:"id" json:"id"`
	TripID    string           `db:"trip_id" json:"trip_id"`
	UserID    string           `db:"user_id" json:"user_id"`
	Role      MembershipRole   `db:"role" json:"role"`
	Status    MembershipStatus `db:"status" json:"status"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetTripMembers(ctx context.Context, tripID string) ([]*GetTripMembersRow, error) {
	rows, err := q.db.Query(ctx, getTripMembers, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetTripMembersRow{}
	for rows.Next() {
		var i GetTripMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTripMembersForUpdate = `-- name: GetTripMembersForUpdate :many
SELECT id, trip_id, user_id, role, status, created_at, updated_at
FROM trip_memberships
WHERE trip_id = $1 AND status = 'ACTIVE'
FOR UPDATE
`

type GetTripMembersForUpdateRow struct {
	ID        string           `db:"id" json:"id"`
	TripID    string           `db:"trip_id" json:"trip_id"`
	UserID    string           `db:"user_id" json:"user_id"`
	Role      MembershipRole   `db:"role" json:"role"`
	Status    MembershipStatus `db:"status" json:"status"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetTripMembersForUpdate(ctx context.Context, tripID string) ([]*GetTripMembersForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getTripMembersForUpdate, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetTripMembersForUpdateRow{}
	for rows.Next() {
		var i GetTripMembersForUpdateRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRole = `-- name: GetUserRole :one
SELECT role
FROM trip_memberships
WHERE trip_id = $1 AND user_id = $2 AND status = 'ACTIVE'
`

type GetUserRoleParams struct {
	TripID string `db:"trip_id" json:"trip_id"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) GetUserRole(ctx context.Context, arg GetUserRoleParams) (MembershipRole, error) {
	row := q.db.QueryRow(ctx, getUserRole, arg.TripID, arg.UserID)
	var role MembershipRole
	err := row.Scan(&role)
	return role, err
}

const isUserMember = `-- name: IsUserMember :one
SELECT EXISTS(
    SELECT 1 FROM trip_memberships
    WHERE trip_id = $1 AND user_id = $2 AND status = 'ACTIVE'
) as is_member
`

type IsUserMemberParams struct {
	TripID string `db:"trip_id" json:"trip_id"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) IsUserMember(ctx context.Context, arg IsUserMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserMember, arg.TripID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE trip_memberships
SET role = $3, updated_at = CURRENT_TIMESTAMP
WHERE trip_id = $1 AND user_id = $2 AND status = 'ACTIVE'
`

type UpdateMemberRoleParams struct {
	TripID string         `db:"trip_id" json:"trip_id"`
	UserID string         `db:"user_id" json:"user_id"`
	Role   MembershipRole `db:"role" json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.TripID, arg.UserID, arg.Role)
	return err
}

const upsertMembership = `-- name: UpsertMembership :exec
INSERT INTO trip_memberships (trip_id, user_id, role, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT (trip_id, user_id)
DO UPDATE SET
    role = EXCLUDED.role,
    status = EXCLUDED.status,
    deleted_at = NULL,
    updated_at = CURRENT_TIMESTAMP
WHERE trip_memberships.status != EXCLUDED.status
   OR trip_memberships.deleted_at IS NOT NULL
`

type UpsertMembershipParams struct {
	TripID string           `db:"trip_id" json:"trip_id"`
	UserID string           `db:"user_id" json:"user_id"`
	Role   MembershipRole   `db:"role" json:"role"`
	Status MembershipStatus `db:"status" json:"status"`
}

func (q *Queries) UpsertMembership(ctx context.Context, arg UpsertMembershipParams) error {
	_, err := q.db.Exec(ctx, upsertMembership,
		arg.TripID,
		arg.UserID,
		arg.Role,
		arg.Status,
	)
	return err
}
