// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"
)

const countAllNotifications = `-- name: CountAllNotifications :one
SELECT COUNT(*) as count
FROM notifications
WHERE user_id = $1
`

func (q *Queries) CountAllNotifications(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAllNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) as count
FROM notifications
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (user_id, type, metadata, is_read)
VALUES ($1, $2, $3, false)
RETURNING id
`

type CreateNotificationParams struct {
	UserID   string           `db:"user_id" json:"user_id"`
	Type     NotificationType `db:"type" json:"type"`
	Metadata []byte           `db:"metadata" json:"metadata"`
}

// Notifications Operations
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (string, error) {
	row := q.db.QueryRow(ctx, createNotification, arg.UserID, arg.Type, arg.Metadata)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteAllNotificationsByUser = `-- name: DeleteAllNotificationsByUser :exec
DELETE FROM notifications
WHERE user_id = $1
`

func (q *Queries) DeleteAllNotificationsByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAllNotificationsByUser, userID)
	return err
}

const deleteNotification = `-- name: DeleteNotification :one
DELETE FROM notifications
WHERE id = $1 AND user_id = $2
RETURNING id
`

type DeleteNotificationParams struct {
	ID     string `db:"id" json:"id"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteNotification, arg.ID, arg.UserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications
WHERE created_at < CURRENT_TIMESTAMP - INTERVAL '30 days'
`

func (q *Queries) DeleteOldNotifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldNotifications)
	return err
}

const getNotification = `-- name: GetNotification :one
SELECT id, user_id, type, metadata, is_read, created_at, updated_at
FROM notifications
WHERE id = $1
`

func (q *Queries) GetNotification(ctx context.Context, id string) (*Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Metadata,
		&i.IsRead,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getReadNotifications = `-- name: GetReadNotifications :many
SELECT id, user_id, type, metadata, is_read, created_at, updated_at
FROM notifications
WHERE user_id = $1 AND is_read = true
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetReadNotificationsParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) GetReadNotifications(ctx context.Context, arg GetReadNotificationsParams) ([]*Notification, error) {
	rows, err := q.db.Query(ctx, getReadNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Metadata,
			&i.IsRead,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadNotifications = `-- name: GetUnreadNotifications :many
SELECT id, user_id, type, metadata, is_read, created_at, updated_at
FROM notifications
WHERE user_id = $1 AND is_read = false
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUnreadNotificationsParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) GetUnreadNotifications(ctx context.Context, arg GetUnreadNotificationsParams) ([]*Notification, error) {
	rows, err := q.db.Query(ctx, getUnreadNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Metadata,
			&i.IsRead,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserNotifications = `-- name: GetUserNotifications :many
SELECT id, user_id, type, metadata, is_read, created_at, updated_at
FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUserNotificationsParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) GetUserNotifications(ctx context.Context, arg GetUserNotificationsParams) ([]*Notification, error) {
	rows, err := q.db.Query(ctx, getUserNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Metadata,
			&i.IsRead,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET is_read = true, updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :one
UPDATE notifications
SET is_read = true, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2
RETURNING id
`

type MarkNotificationAsReadParams struct {
	ID     string `db:"id" json:"id"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (string, error) {
	row := q.db.QueryRow(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	var id string
	err := row.Scan(&id)
	return id, err
}
