// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddChatGroupMember(ctx context.Context, arg AddChatGroupMemberParams) error
	AddMessageReaction(ctx context.Context, arg AddMessageReactionParams) error
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	CheckUsernameExists(ctx context.Context, username string) (bool, error)
	CountCompletedTodosByTrip(ctx context.Context, tripID string) (int64, error)
	CountPendingInvitationsForTrip(ctx context.Context, tripID string) (int64, error)
	CountTodosByTrip(ctx context.Context, tripID string) (int64, error)
	CountTripMembers(ctx context.Context, tripID string) (int64, error)
	CountUnreadMessages(ctx context.Context, arg CountUnreadMessagesParams) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID string) (int64, error)
	// Chat Operations
	CreateChatGroup(ctx context.Context, arg CreateChatGroupParams) (string, error)
	CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (string, error)
	// Trip Invitations Operations
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (string, error)
	// Locations Operations
	CreateLocation(ctx context.Context, arg CreateLocationParams) (string, error)
	// Trip Memberships Operations
	CreateMembership(ctx context.Context, arg CreateMembershipParams) error
	// Notifications Operations
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (string, error)
	// Todos Operations
	CreateTodo(ctx context.Context, arg CreateTodoParams) (string, error)
	// Trips CRUD Operations
	CreateTrip(ctx context.Context, arg CreateTripParams) (string, error)
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (string, error)
	DeactivateMembership(ctx context.Context, arg DeactivateMembershipParams) error
	DeleteExpiredInvitations(ctx context.Context) error
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error
	DeleteOldNotifications(ctx context.Context) error
	// Disable location sharing that has expired
	DisableExpiredSharing(ctx context.Context) error
	GetActiveMembership(ctx context.Context, arg GetActiveMembershipParams) (*GetActiveMembershipRow, error)
	GetChatGroup(ctx context.Context, id string) (*GetChatGroupRow, error)
	GetChatGroupByTrip(ctx context.Context, tripID string) (*GetChatGroupByTripRow, error)
	GetChatGroupMembers(ctx context.Context, groupID string) ([]*ChatGroupMember, error)
	GetChatMessage(ctx context.Context, id string) (*GetChatMessageRow, error)
	GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]*GetChatMessagesRow, error)
	// Get messages after a specific timestamp (for real-time updates)
	GetChatMessagesAfter(ctx context.Context, arg GetChatMessagesAfterParams) ([]*GetChatMessagesAfterRow, error)
	GetInvitation(ctx context.Context, id string) (*GetInvitationRow, error)
	GetInvitationByToken(ctx context.Context, token *string) (*GetInvitationByTokenRow, error)
	GetInvitationsByTripID(ctx context.Context, tripID string) ([]*GetInvitationsByTripIDRow, error)
	GetLastReadMessageID(ctx context.Context, arg GetLastReadMessageIDParams) (*string, error)
	GetLocation(ctx context.Context, id string) (*GetLocationRow, error)
	// Get members with user profile information
	GetMemberWithUserDetails(ctx context.Context, tripID string) ([]*GetMemberWithUserDetailsRow, error)
	GetMembership(ctx context.Context, arg GetMembershipParams) (*GetMembershipRow, error)
	GetMessageReactions(ctx context.Context, messageID string) ([]*ChatMessageReaction, error)
	GetNotification(ctx context.Context, id string) (*Notification, error)
	GetPendingInvitationsForUser(ctx context.Context, inviteeEmail string) ([]*GetPendingInvitationsForUserRow, error)
	GetTodo(ctx context.Context, id string) (*GetTodoRow, error)
	GetTrip(ctx context.Context, id string) (*GetTripRow, error)
	// Get a trip that a specific user is a member of
	GetTripForMember(ctx context.Context, arg GetTripForMemberParams) (*GetTripForMemberRow, error)
	// Get latest locations for all members of a trip
	GetTripMemberLocations(ctx context.Context, tripID string) ([]*GetTripMemberLocationsRow, error)
	GetTripMembers(ctx context.Context, tripID string) ([]*GetTripMembersRow, error)
	GetTripStatus(ctx context.Context, id string) (*GetTripStatusRow, error)
	GetUnreadNotifications(ctx context.Context, userID string) ([]*Notification, error)
	// Get the latest location for a user in a specific trip
	GetUserLocationInTrip(ctx context.Context, arg GetUserLocationInTripParams) (*GetUserLocationInTripRow, error)
	GetUserNotifications(ctx context.Context, arg GetUserNotificationsParams) ([]*Notification, error)
	GetUserProfileByEmail(ctx context.Context, email string) (*GetUserProfileByEmailRow, error)
	// Users Operations (using user_profiles table)
	GetUserProfileByID(ctx context.Context, id string) (*GetUserProfileByIDRow, error)
	GetUserProfileByUsername(ctx context.Context, username string) (*GetUserProfileByUsernameRow, error)
	GetUserRole(ctx context.Context, arg GetUserRoleParams) (MembershipRole, error)
	IsUserMember(ctx context.Context, arg IsUserMemberParams) (bool, error)
	// Get all trips where user is a member (active membership)
	ListMemberTrips(ctx context.Context, userID string) ([]*ListMemberTripsRow, error)
	ListTodosByTrip(ctx context.Context, tripID string) ([]*ListTodosByTripRow, error)
	ListTodosByUser(ctx context.Context, createdBy string) ([]*ListTodosByUserRow, error)
	ListUserProfiles(ctx context.Context, arg ListUserProfilesParams) ([]*ListUserProfilesRow, error)
	// Get all trips created by a specific user
	ListUserTrips(ctx context.Context, createdBy *string) ([]*ListUserTripsRow, error)
	MarkAllNotificationsRead(ctx context.Context, userID string) error
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error
	RemoveChatGroupMember(ctx context.Context, arg RemoveChatGroupMemberParams) error
	RemoveMessageReaction(ctx context.Context, arg RemoveMessageReactionParams) error
	// Search trips by destination name/address with optional date filters
	SearchTrips(ctx context.Context, arg SearchTripsParams) ([]*SearchTripsRow, error)
	SearchUserProfiles(ctx context.Context, dollar_1 *string) ([]*SearchUserProfilesRow, error)
	SoftDeleteChatMessage(ctx context.Context, arg SoftDeleteChatMessageParams) error
	SoftDeleteLocation(ctx context.Context, id string) error
	SoftDeleteTodo(ctx context.Context, id string) error
	SoftDeleteTrip(ctx context.Context, id string) error
	UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) error
	UpdateLastReadMessage(ctx context.Context, arg UpdateLastReadMessageParams) error
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) error
	UpdateLocationPrivacy(ctx context.Context, arg UpdateLocationPrivacyParams) error
	UpdateLocationSharing(ctx context.Context, arg UpdateLocationSharingParams) error
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error
	UpdateTodoStatus(ctx context.Context, arg UpdateTodoStatusParams) error
	UpdateTodoText(ctx context.Context, arg UpdateTodoTextParams) error
	UpdateTripDates(ctx context.Context, arg UpdateTripDatesParams) error
	UpdateTripDescription(ctx context.Context, arg UpdateTripDescriptionParams) error
	UpdateTripDestination(ctx context.Context, arg UpdateTripDestinationParams) error
	UpdateTripName(ctx context.Context, arg UpdateTripNameParams) error
	UpdateTripStatus(ctx context.Context, arg UpdateTripStatusParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	UpsertMembership(ctx context.Context, arg UpsertMembershipParams) error
	UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (string, error)
}

var _ Querier = (*Queries)(nil)
