// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCompletedTodosByTrip = `-- name: CountCompletedTodosByTrip :one
SELECT COUNT(*) as count
FROM todos
WHERE trip_id = $1 AND status = 'COMPLETE' AND deleted_at IS NULL
`

func (q *Queries) CountCompletedTodosByTrip(ctx context.Context, tripID string) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedTodosByTrip, tripID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTodosByTrip = `-- name: CountTodosByTrip :one
SELECT COUNT(*) as count
FROM todos
WHERE trip_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountTodosByTrip(ctx context.Context, tripID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTodosByTrip, tripID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTodo = `-- name: CreateTodo :one

INSERT INTO todos (trip_id, text, status, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateTodoParams struct {
	TripID    string     `db:"trip_id" json:"trip_id"`
	Text      string     `db:"text" json:"text"`
	Status    TodoStatus `db:"status" json:"status"`
	CreatedBy string     `db:"created_by" json:"created_by"`
}

// Todos Operations
func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (string, error) {
	row := q.db.QueryRow(ctx, createTodo,
		arg.TripID,
		arg.Text,
		arg.Status,
		arg.CreatedBy,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getTodo = `-- name: GetTodo :one
SELECT id, trip_id, text, status, created_by, created_at, updated_at
FROM todos
WHERE id = $1 AND deleted_at IS NULL
`

type GetTodoRow struct {
	ID        string             `db:"id" json:"id"`
	TripID    string             `db:"trip_id" json:"trip_id"`
	Text      string             `db:"text" json:"text"`
	Status    TodoStatus         `db:"status" json:"status"`
	CreatedBy string             `db:"created_by" json:"created_by"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetTodo(ctx context.Context, id string) (*GetTodoRow, error) {
	row := q.db.QueryRow(ctx, getTodo, id)
	var i GetTodoRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Text,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listTodosByTrip = `-- name: ListTodosByTrip :many
SELECT id, trip_id, text, status, created_by, created_at, updated_at
FROM todos
WHERE trip_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListTodosByTripRow struct {
	ID        string             `db:"id" json:"id"`
	TripID    string             `db:"trip_id" json:"trip_id"`
	Text      string             `db:"text" json:"text"`
	Status    TodoStatus         `db:"status" json:"status"`
	CreatedBy string             `db:"created_by" json:"created_by"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListTodosByTrip(ctx context.Context, tripID string) ([]*ListTodosByTripRow, error) {
	rows, err := q.db.Query(ctx, listTodosByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListTodosByTripRow{}
	for rows.Next() {
		var i ListTodosByTripRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Text,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosByUser = `-- name: ListTodosByUser :many
SELECT id, trip_id, text, status, created_by, created_at, updated_at
FROM todos
WHERE created_by = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListTodosByUserRow struct {
	ID        string             `db:"id" json:"id"`
	TripID    string             `db:"trip_id" json:"trip_id"`
	Text      string             `db:"text" json:"text"`
	Status    TodoStatus         `db:"status" json:"status"`
	CreatedBy string             `db:"created_by" json:"created_by"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListTodosByUser(ctx context.Context, createdBy string) ([]*ListTodosByUserRow, error) {
	rows, err := q.db.Query(ctx, listTodosByUser, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListTodosByUserRow{}
	for rows.Next() {
		var i ListTodosByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Text,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTodo = `-- name: SoftDeleteTodo :exec
UPDATE todos
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTodo(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteTodo, id)
	return err
}

const updateTodoStatus = `-- name: UpdateTodoStatus :exec
UPDATE todos
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateTodoStatusParams struct {
	ID     string     `db:"id" json:"id"`
	Status TodoStatus `db:"status" json:"status"`
}

func (q *Queries) UpdateTodoStatus(ctx context.Context, arg UpdateTodoStatusParams) error {
	_, err := q.db.Exec(ctx, updateTodoStatus, arg.ID, arg.Status)
	return err
}

const updateTodoText = `-- name: UpdateTodoText :exec
UPDATE todos
SET text = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateTodoTextParams struct {
	ID   string `db:"id" json:"id"`
	Text string `db:"text" json:"text"`
}

func (q *Queries) UpdateTodoText(ctx context.Context, arg UpdateTodoTextParams) error {
	_, err := q.db.Exec(ctx, updateTodoText, arg.ID, arg.Text)
	return err
}
