// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS(SELECT 1 FROM user_profiles WHERE email = $1) as exists
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT EXISTS(SELECT 1 FROM user_profiles WHERE username = $1) as exists
`

func (q *Queries) CheckUsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUsernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (id, email, username, first_name, last_name, avatar_url)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateUserProfileParams struct {
	ID        string `db:"id" json:"id"`
	Email     string `db:"email" json:"email"`
	Username  string `db:"username" json:"username"`
	FirstName string `db:"first_name" json:"first_name"`
	LastName  string `db:"last_name" json:"last_name"`
	AvatarUrl string `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (string, error) {
	row := q.db.QueryRow(ctx, createUserProfile,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getUserProfileByEmail = `-- name: GetUserProfileByEmail :one
SELECT
    id, email, username,
    COALESCE(first_name, '') as first_name,
    COALESCE(last_name, '') as last_name,
    COALESCE(avatar_url, '') as avatar_url,
    created_at, updated_at
FROM user_profiles
WHERE email = $1
`

type GetUserProfileByEmailRow struct {
	ID        string             `db:"id" json:"id"`
	Email     string             `db:"email" json:"email"`
	Username  string             `db:"username" json:"username"`
	FirstName string             `db:"first_name" json:"first_name"`
	LastName  string             `db:"last_name" json:"last_name"`
	AvatarUrl string             `db:"avatar_url" json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUserProfileByEmail(ctx context.Context, email string) (*GetUserProfileByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserProfileByEmail, email)
	var i GetUserProfileByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserProfileByID = `-- name: GetUserProfileByID :one

SELECT
    id, email, username,
    COALESCE(first_name, '') as first_name,
    COALESCE(last_name, '') as last_name,
    COALESCE(avatar_url, '') as avatar_url,
    created_at, updated_at
FROM user_profiles
WHERE id = $1
`

type GetUserProfileByIDRow struct {
	ID        string             `db:"id" json:"id"`
	Email     string             `db:"email" json:"email"`
	Username  string             `db:"username" json:"username"`
	FirstName string             `db:"first_name" json:"first_name"`
	LastName  string             `db:"last_name" json:"last_name"`
	AvatarUrl string             `db:"avatar_url" json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Users Operations (using user_profiles table)
func (q *Queries) GetUserProfileByID(ctx context.Context, id string) (*GetUserProfileByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserProfileByID, id)
	var i GetUserProfileByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserProfileByUsername = `-- name: GetUserProfileByUsername :one
SELECT
    id, email, username,
    COALESCE(first_name, '') as first_name,
    COALESCE(last_name, '') as last_name,
    COALESCE(avatar_url, '') as avatar_url,
    created_at, updated_at
FROM user_profiles
WHERE username = $1
`

type GetUserProfileByUsernameRow struct {
	ID        string             `db:"id" json:"id"`
	Email     string             `db:"email" json:"email"`
	Username  string             `db:"username" json:"username"`
	FirstName string             `db:"first_name" json:"first_name"`
	LastName  string             `db:"last_name" json:"last_name"`
	AvatarUrl string             `db:"avatar_url" json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUserProfileByUsername(ctx context.Context, username string) (*GetUserProfileByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserProfileByUsername, username)
	var i GetUserProfileByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listUserProfiles = `-- name: ListUserProfiles :many
SELECT
    id, email, username,
    COALESCE(first_name, '') as first_name,
    COALESCE(last_name, '') as last_name,
    COALESCE(avatar_url, '') as avatar_url,
    created_at, updated_at
FROM user_profiles
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUserProfilesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListUserProfilesRow struct {
	ID        string             `db:"id" json:"id"`
	Email     string             `db:"email" json:"email"`
	Username  string             `db:"username" json:"username"`
	FirstName string             `db:"first_name" json:"first_name"`
	LastName  string             `db:"last_name" json:"last_name"`
	AvatarUrl string             `db:"avatar_url" json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListUserProfiles(ctx context.Context, arg ListUserProfilesParams) ([]*ListUserProfilesRow, error) {
	rows, err := q.db.Query(ctx, listUserProfiles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListUserProfilesRow{}
	for rows.Next() {
		var i ListUserProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUserProfiles = `-- name: SearchUserProfiles :many
SELECT
    id, email, username,
    COALESCE(first_name, '') as first_name,
    COALESCE(last_name, '') as last_name,
    COALESCE(avatar_url, '') as avatar_url,
    created_at, updated_at
FROM user_profiles
WHERE
    username ILIKE '%' || $1 || '%'
    OR email ILIKE '%' || $1 || '%'
ORDER BY username ASC
LIMIT 20
`

type SearchUserProfilesRow struct {
	ID        string             `db:"id" json:"id"`
	Email     string             `db:"email" json:"email"`
	Username  string             `db:"username" json:"username"`
	FirstName string             `db:"first_name" json:"first_name"`
	LastName  string             `db:"last_name" json:"last_name"`
	AvatarUrl string             `db:"avatar_url" json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) SearchUserProfiles(ctx context.Context, dollar_1 *string) ([]*SearchUserProfilesRow, error) {
	rows, err := q.db.Query(ctx, searchUserProfiles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*SearchUserProfilesRow{}
	for rows.Next() {
		var i SearchUserProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.FirstName,
			&i.LastName,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE user_profiles
SET
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    avatar_url = COALESCE($4, avatar_url),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID        string  `db:"id" json:"id"`
	FirstName *string `db:"first_name" json:"first_name"`
	LastName  *string `db:"last_name" json:"last_name"`
	AvatarUrl *string `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
	)
	return err
}

const upsertUserProfile = `-- name: UpsertUserProfile :one
INSERT INTO user_profiles (id, email, username, first_name, last_name, avatar_url)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id)
DO UPDATE SET
    email = EXCLUDED.email,
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = CURRENT_TIMESTAMP
RETURNING id
`

type UpsertUserProfileParams struct {
	ID        string `db:"id" json:"id"`
	Email     string `db:"email" json:"email"`
	Username  string `db:"username" json:"username"`
	FirstName string `db:"first_name" json:"first_name"`
	LastName  string `db:"last_name" json:"last_name"`
	AvatarUrl string `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertUserProfile,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.AvatarUrl,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
