name: AWS Infrastructure Deployment - Production

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - 'LICENSE'
      - '**/*.{png,jpg}'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-workflow:
    uses: ./.github/workflows/terraform-workflow.yml
    with:
      environment: production
      terraform_dir: deployment/terraform
      role_arn: arn:aws:iam::195275657852:role/NomadCrewProductionDeploymentRole
      aws_region: us-east-2
      ecr_repository: nomadcrew
      terraform_version: 1.5.7
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      GOOGLE_WEB_CLIENT_ID: ${{ secrets.GOOGLE_WEB_CLIENT_ID }}
      GOOGLE_PLACES_API_KEY: ${{ secrets.GOOGLE_PLACES_API_KEY }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      GEOAPIFY_KEY: ${{ secrets.GEOAPIFY_KEY }}
      PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      SUPABASE_JWT_SECRET: ${{ secrets.SUPABASE_JWT_SECRET }}
      EMAIL_FROM_ADDRESS: ${{ secrets.EMAIL_FROM_ADDRESS }}
      EMAIL_FROM_NAME: ${{ secrets.EMAIL_FROM_NAME }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}