name: golangci-lint
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      
      - name: Get dependencies
        run: |
          go mod download
          go mod verify
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          args: --timeout=5m
          working-directory: ./

    env:
      GOFLAGS: "-buildvcs=false"
      GOCACHE: "/home/runner/.cache/go-build"
      GOMODCACHE: "/home/runner/go/pkg/mod"