name: golangci-lint
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'  # Specify a concrete version
      - name: Get dependencies
        run: |
          go mod download
          go mod verify
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          args: --timeout=5m
          only-new-issues: true
          working-directory: ./
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
    env:
      GOFLAGS: "-buildvcs=false"  # Speeds up builds in CI
      GOCACHE: "$HOME/.cache/go-build"
      GOMODCACHE: "$HOME/go/pkg/mod"