name: golangci-lint
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
    paths-ignore:
      - '**.md'
      - 'docs/**'

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      
      - name: Configure Go environment
        run: |
          echo "GOCACHE=/home/runner/.cache/go-build" >> $GITHUB_ENV
          echo "GOMODCACHE=/home/runner/go/pkg/mod" >> $GITHUB_ENV
          mkdir -p "$GOCACHE"
          mkdir -p "$GOMODCACHE"
      
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/go/pkg/mod
            /home/runner/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Get dependencies
        run: |
          go mod download
          go mod verify
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          args: --timeout=5m
          only-new-issues: true
          working-directory: ./